@startuml
'https://plantuml.com/class-diagram

title 继承

class Vehicle {
  name
  toString() : String
}

class Car {
  toString() : String
}

class Bike {
  toString() : String
}

class Trunk {
  toString() : String
}

Vehicle <|-- Car
Vehicle <|-- Bike
Vehicle <|-- Trunk

@enduml